import Head from 'next/head'
import { useState } from 'react';
import ContactSendGrid from './components/ContactSendGrid';


export default function Home() {
	

	return (
		<div className="">
			<Head>
				<title>React Form Send Grid</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <main>
        <ContactSendGrid/>
      </main>
		
		</div>
	);
}
